#!/bin/bash -x

# Author: Paolo Cumani, Tarek Hassan, Abelardo Moralejo

# ATTENTION: VALUES TO CHANGE!!! CHANGE ALSO THE PATH TO THE DIFFERENT FILES!!!

# - Check and Set environment
echo " - Setting up environment ... "
source setupPackageMARS.sh

baseoutpath="/vo.cta.in2p3.fr/user/p/pcumani"

direction=$1
site=$2
diffuse=$3
telType=$4
zenName=$5
lfnFilesGammas=`ls ./ | grep "gamma_ghtrain"`
lfnFilesProtons=`ls ./ | grep "proton_ghtrain"`
StatFile=`ls ./ | grep "Statistic_train.txt"`

RFLABEL="final100k"

if [ $direction == "N" ]; then
	directionname="north"
else
	directionname="south"
fi

maxjobsERF=`cat ${StatFile} | grep "E_${telType}_${direction}_${zenName}_${diffuse}" | awk -F "_" '{print $6}'`

# The next line is needed because Luisa's stereo files contains 1 .root per tarball. The one generated by me to
# train the Energy RF contain 5 of them (and we do NOT want to use them twice)
let maxjobsERF=5*maxjobsERF

maxjobsRFgamma=`cat ${StatFile} | grep "Gh_gamma_${telType}_${direction}_${zenName}_${diffuse}" | awk -F "_" '{print $7}'`
maxjobsRFproton=`cat ${StatFile} | grep "Gh_proton_${telType}_${direction}_${zenName}_${diffuse}" | awk -F "_" '{print $7}'`

# Quick way to pass from 150000 images to 100000 images without updating the StatFile WARNING: this usually should be commented
#let maxjobsRFgamma=(maxjobsRFgamma/3)*2+1
#let maxjobsRFproton=(maxjobsRFproton/3)*2+1

# Exclude the gamma files already used for the training of the Energy RF and download only a maxjobs number of files
tail -n +${maxjobsERF} "$lfnFilesGammas" > tempGammaSet.lfns
head -${maxjobsRFgamma} tempGammaSet.lfns > finalGammaSet.lfns
head -${maxjobsRFproton} "$lfnFilesProtons" > finalProtonSet.lfns

rm $MARSSYS/macros/CTAtrain.C
mv ./CTAtrain.C $MARSSYS/macros

# copy input files
dirac-dms-get-file finalGammaSet.lfns
if [ $? -gt 0 ]; then
	# - Finish
	echo " - Could not download gamma files. Exiting..."
	exit 1
fi

dirac-dms-get-file finalProtonSet.lfns
if [ $? -gt 0 ]; then
	# - Finish
	echo " - Could not download proton files. Exiting..."
	exit 2
fi

ls

root.exe -l -b -q "${MARSSYS}/macros/CTAtrain.C+(\"*_S_${diffuse}.root\", \"\", 2, kFALSE, kFALSE, $telType, $telType)"
if [ $? -gt 0 ]; then
	# - Finish
	echo " - CTAtrain.C macro was not happy... :( "
	exit 3
fi

ls

filename="RF_${zenName}_${diffuse}_files_${direction}_${telType}_${RFLABEL}.tgz"

tar zcf $filename  RF*.root

if [ $? -gt 0 ]; then
	# - Finish
	echo " - Could not create tar file "
	exit 4
fi

dirac-dms-remove-files ${baseoutpath}/MC/PROD3/PARANAL/3HB9/${zenName}/${diffuse}/${directionname}/$filename
dirac-dms-add-file ${baseoutpath}/MC/PROD3/PARANAL/3HB9/${zenName}/${diffuse}/${directionname}/$filename $filename CC-IN2P3-USER

if [ $? -gt 0 ]; then
	# - Finish
	echo " - Could not upload the resulting tar file"
	exit 5
fi

exit 0
